// Code generated by protoc-gen-go. DO NOT EDIT.
// source: token.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetTokenRequest struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Scope                []string `protobuf:"bytes,2,rep,name=scope,proto3" json:"scope,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenRequest) Reset()         { *m = GetTokenRequest{} }
func (m *GetTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetTokenRequest) ProtoMessage()    {}
func (*GetTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{0}
}

func (m *GetTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenRequest.Unmarshal(m, b)
}
func (m *GetTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenRequest.Marshal(b, m, deterministic)
}
func (m *GetTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenRequest.Merge(m, src)
}
func (m *GetTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GetTokenRequest.Size(m)
}
func (m *GetTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenRequest proto.InternalMessageInfo

func (m *GetTokenRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *GetTokenRequest) GetScope() []string {
	if m != nil {
		return m.Scope
	}
	return nil
}

func (m *GetTokenRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type GetTokenResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenResponse) Reset()         { *m = GetTokenResponse{} }
func (m *GetTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GetTokenResponse) ProtoMessage()    {}
func (*GetTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{1}
}

func (m *GetTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenResponse.Unmarshal(m, b)
}
func (m *GetTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenResponse.Marshal(b, m, deterministic)
}
func (m *GetTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenResponse.Merge(m, src)
}
func (m *GetTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GetTokenResponse.Size(m)
}
func (m *GetTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenResponse proto.InternalMessageInfo

func (m *GetTokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type SetTokenRequest struct {
	Host                 string               `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Scope                []string             `protobuf:"bytes,2,rep,name=scope,proto3" json:"scope,omitempty"`
	Token                string               `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	ExpiryDate           *timestamp.Timestamp `protobuf:"bytes,4,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SetTokenRequest) Reset()         { *m = SetTokenRequest{} }
func (m *SetTokenRequest) String() string { return proto.CompactTextString(m) }
func (*SetTokenRequest) ProtoMessage()    {}
func (*SetTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{2}
}

func (m *SetTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetTokenRequest.Unmarshal(m, b)
}
func (m *SetTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetTokenRequest.Marshal(b, m, deterministic)
}
func (m *SetTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetTokenRequest.Merge(m, src)
}
func (m *SetTokenRequest) XXX_Size() int {
	return xxx_messageInfo_SetTokenRequest.Size(m)
}
func (m *SetTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetTokenRequest proto.InternalMessageInfo

func (m *SetTokenRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *SetTokenRequest) GetScope() []string {
	if m != nil {
		return m.Scope
	}
	return nil
}

func (m *SetTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *SetTokenRequest) GetExpiryDate() *timestamp.Timestamp {
	if m != nil {
		return m.ExpiryDate
	}
	return nil
}

type SetTokenResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetTokenResponse) Reset()         { *m = SetTokenResponse{} }
func (m *SetTokenResponse) String() string { return proto.CompactTextString(m) }
func (*SetTokenResponse) ProtoMessage()    {}
func (*SetTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{3}
}

func (m *SetTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetTokenResponse.Unmarshal(m, b)
}
func (m *SetTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetTokenResponse.Marshal(b, m, deterministic)
}
func (m *SetTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetTokenResponse.Merge(m, src)
}
func (m *SetTokenResponse) XXX_Size() int {
	return xxx_messageInfo_SetTokenResponse.Size(m)
}
func (m *SetTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetTokenResponse proto.InternalMessageInfo

type ProvideTokenRequest struct {
	// Types that are valid to be assigned to Message:
	//	*ProvideTokenRequest_Registration
	//	*ProvideTokenRequest_Answer
	Message              isProvideTokenRequest_Message `protobuf_oneof:"message"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ProvideTokenRequest) Reset()         { *m = ProvideTokenRequest{} }
func (m *ProvideTokenRequest) String() string { return proto.CompactTextString(m) }
func (*ProvideTokenRequest) ProtoMessage()    {}
func (*ProvideTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{4}
}

func (m *ProvideTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvideTokenRequest.Unmarshal(m, b)
}
func (m *ProvideTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvideTokenRequest.Marshal(b, m, deterministic)
}
func (m *ProvideTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvideTokenRequest.Merge(m, src)
}
func (m *ProvideTokenRequest) XXX_Size() int {
	return xxx_messageInfo_ProvideTokenRequest.Size(m)
}
func (m *ProvideTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvideTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProvideTokenRequest proto.InternalMessageInfo

type isProvideTokenRequest_Message interface {
	isProvideTokenRequest_Message()
}

type ProvideTokenRequest_Registration struct {
	Registration *ProvideTokenRequest_RegisterProvider `protobuf:"bytes,1,opt,name=registration,proto3,oneof"`
}

type ProvideTokenRequest_Answer struct {
	Answer *SetTokenRequest `protobuf:"bytes,2,opt,name=answer,proto3,oneof"`
}

func (*ProvideTokenRequest_Registration) isProvideTokenRequest_Message() {}

func (*ProvideTokenRequest_Answer) isProvideTokenRequest_Message() {}

func (m *ProvideTokenRequest) GetMessage() isProvideTokenRequest_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *ProvideTokenRequest) GetRegistration() *ProvideTokenRequest_RegisterProvider {
	if x, ok := m.GetMessage().(*ProvideTokenRequest_Registration); ok {
		return x.Registration
	}
	return nil
}

func (m *ProvideTokenRequest) GetAnswer() *SetTokenRequest {
	if x, ok := m.GetMessage().(*ProvideTokenRequest_Answer); ok {
		return x.Answer
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ProvideTokenRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ProvideTokenRequest_Registration)(nil),
		(*ProvideTokenRequest_Answer)(nil),
	}
}

type ProvideTokenRequest_RegisterProvider struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProvideTokenRequest_RegisterProvider) Reset()         { *m = ProvideTokenRequest_RegisterProvider{} }
func (m *ProvideTokenRequest_RegisterProvider) String() string { return proto.CompactTextString(m) }
func (*ProvideTokenRequest_RegisterProvider) ProtoMessage()    {}
func (*ProvideTokenRequest_RegisterProvider) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{4, 0}
}

func (m *ProvideTokenRequest_RegisterProvider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvideTokenRequest_RegisterProvider.Unmarshal(m, b)
}
func (m *ProvideTokenRequest_RegisterProvider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvideTokenRequest_RegisterProvider.Marshal(b, m, deterministic)
}
func (m *ProvideTokenRequest_RegisterProvider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvideTokenRequest_RegisterProvider.Merge(m, src)
}
func (m *ProvideTokenRequest_RegisterProvider) XXX_Size() int {
	return xxx_messageInfo_ProvideTokenRequest_RegisterProvider.Size(m)
}
func (m *ProvideTokenRequest_RegisterProvider) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvideTokenRequest_RegisterProvider.DiscardUnknown(m)
}

var xxx_messageInfo_ProvideTokenRequest_RegisterProvider proto.InternalMessageInfo

func (m *ProvideTokenRequest_RegisterProvider) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

type ProvideTokenResponse struct {
	Request              *GetTokenRequest `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ProvideTokenResponse) Reset()         { *m = ProvideTokenResponse{} }
func (m *ProvideTokenResponse) String() string { return proto.CompactTextString(m) }
func (*ProvideTokenResponse) ProtoMessage()    {}
func (*ProvideTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{5}
}

func (m *ProvideTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProvideTokenResponse.Unmarshal(m, b)
}
func (m *ProvideTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProvideTokenResponse.Marshal(b, m, deterministic)
}
func (m *ProvideTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvideTokenResponse.Merge(m, src)
}
func (m *ProvideTokenResponse) XXX_Size() int {
	return xxx_messageInfo_ProvideTokenResponse.Size(m)
}
func (m *ProvideTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvideTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProvideTokenResponse proto.InternalMessageInfo

func (m *ProvideTokenResponse) GetRequest() *GetTokenRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

func init() {
	proto.RegisterType((*GetTokenRequest)(nil), "supervisor.GetTokenRequest")
	proto.RegisterType((*GetTokenResponse)(nil), "supervisor.GetTokenResponse")
	proto.RegisterType((*SetTokenRequest)(nil), "supervisor.SetTokenRequest")
	proto.RegisterType((*SetTokenResponse)(nil), "supervisor.SetTokenResponse")
	proto.RegisterType((*ProvideTokenRequest)(nil), "supervisor.ProvideTokenRequest")
	proto.RegisterType((*ProvideTokenRequest_RegisterProvider)(nil), "supervisor.ProvideTokenRequest.RegisterProvider")
	proto.RegisterType((*ProvideTokenResponse)(nil), "supervisor.ProvideTokenResponse")
}

func init() {
	proto.RegisterFile("token.proto", fileDescriptor_3aff0bcd502840ab)
}

var fileDescriptor_3aff0bcd502840ab = []byte{
	// 457 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x8e, 0x93, 0xfe, 0x90, 0x71, 0xa4, 0x46, 0x4b, 0x0f, 0x96, 0xa9, 0x54, 0xcb, 0x07, 0xe4,
	0x93, 0x5d, 0x82, 0x7a, 0xe2, 0x56, 0x21, 0xd1, 0x0b, 0x12, 0x5a, 0x57, 0x20, 0x21, 0x21, 0xb4,
	0x4d, 0x06, 0xb3, 0x82, 0x78, 0x97, 0xdd, 0x4d, 0x00, 0x55, 0xbd, 0xf0, 0x00, 0x5c, 0x78, 0x1a,
	0x9e, 0x83, 0x03, 0x2f, 0xc0, 0x83, 0x20, 0xaf, 0x37, 0xd4, 0xb6, 0x9c, 0x22, 0xf5, 0xe6, 0xf5,
	0x7c, 0xf3, 0x7d, 0xdf, 0x7c, 0x33, 0xe0, 0x1b, 0xf1, 0x01, 0xcb, 0x54, 0x2a, 0x61, 0x04, 0x01,
	0xbd, 0x92, 0xa8, 0xd6, 0x5c, 0x0b, 0x15, 0x1e, 0x15, 0x42, 0x14, 0x1f, 0x31, 0x63, 0x92, 0x67,
	0xac, 0x2c, 0x85, 0x61, 0x86, 0x8b, 0x52, 0xd7, 0xc8, 0xf0, 0xd8, 0x55, 0xed, 0xeb, 0x72, 0xf5,
	0x2e, 0x33, 0x7c, 0x89, 0xda, 0xb0, 0xa5, 0xac, 0x01, 0xf1, 0x1b, 0x38, 0x78, 0x86, 0xe6, 0xa2,
	0x22, 0xa7, 0xf8, 0x69, 0x85, 0xda, 0x10, 0x02, 0x3b, 0xef, 0x85, 0x36, 0x81, 0x17, 0x79, 0xc9,
	0x98, 0xda, 0x6f, 0x72, 0x08, 0xbb, 0x7a, 0x2e, 0x24, 0x06, 0xc3, 0x68, 0x94, 0x8c, 0x69, 0xfd,
	0x20, 0x11, 0xf8, 0x0b, 0xd4, 0x73, 0xc5, 0x65, 0xa5, 0x19, 0x8c, 0x6c, 0x43, 0xf3, 0x57, 0x9c,
	0xc0, 0xf4, 0x86, 0x5e, 0x4b, 0x51, 0x6a, 0xac, 0xb8, 0xec, 0x30, 0x4e, 0xa0, 0x7e, 0xc4, 0xdf,
	0x3d, 0x38, 0xc8, 0xef, 0xec, 0xe4, 0x1f, 0xe7, 0xa8, 0xc1, 0x49, 0x9e, 0x80, 0x8f, 0x5f, 0x24,
	0x57, 0x5f, 0xdf, 0x2e, 0x98, 0xc1, 0x60, 0x27, 0xf2, 0x12, 0x7f, 0x16, 0xa6, 0x75, 0x26, 0xe9,
	0x26, 0x93, 0xf4, 0x62, 0x93, 0x09, 0x85, 0x1a, 0xfe, 0x94, 0x19, 0x8c, 0x09, 0x4c, 0xf3, 0x8e,
	0xf5, 0xf8, 0xb7, 0x07, 0xf7, 0x5f, 0x28, 0xb1, 0xe6, 0x0b, 0x6c, 0x19, 0x7d, 0x09, 0x13, 0x85,
	0x05, 0xd7, 0x46, 0xd9, 0xf4, 0xad, 0x61, 0x7f, 0x76, 0x92, 0xde, 0xec, 0x29, 0xed, 0x69, 0x4b,
	0xa9, 0xed, 0x41, 0xe5, 0x6a, 0xea, 0x7c, 0x40, 0x5b, 0x3c, 0xe4, 0x14, 0xf6, 0x58, 0xa9, 0x3f,
	0xa3, 0x0a, 0x86, 0x96, 0xf1, 0x41, 0x93, 0xb1, 0x93, 0xd6, 0xf9, 0x80, 0x3a, 0x70, 0xf8, 0x10,
	0xa6, 0x5d, 0xea, 0xbe, 0x2c, 0xcf, 0xc6, 0xb0, 0xbf, 0x44, 0xad, 0x59, 0x81, 0xf1, 0x73, 0x38,
	0x6c, 0x3b, 0x74, 0xcb, 0x3a, 0x85, 0x7d, 0x55, 0xf3, 0xbb, 0xa1, 0x5a, 0x16, 0x3a, 0xa7, 0x43,
	0x37, 0xd8, 0xd9, 0xcf, 0x21, 0x4c, 0x6c, 0x25, 0xaf, 0xa0, 0x73, 0x24, 0x05, 0xdc, 0xdb, 0x80,
	0xc9, 0x6d, 0x14, 0xe1, 0x51, 0x7f, 0xd1, 0x2d, 0x20, 0xfa, 0xf6, 0xeb, 0xcf, 0x8f, 0x61, 0x48,
	0x82, 0x6c, 0xfd, 0x28, 0xb3, 0x4b, 0xce, 0xae, 0xaa, 0x51, 0xae, 0xb3, 0x2b, 0x7b, 0x08, 0xd7,
	0x95, 0x50, 0xde, 0x2b, 0x94, 0xdf, 0x26, 0x94, 0x6f, 0x11, 0x8a, 0xb7, 0x0b, 0xbd, 0x82, 0x49,
	0x33, 0x31, 0x72, 0xfc, 0x9f, 0x6d, 0x87, 0xd1, 0x76, 0x80, 0x13, 0x1d, 0x24, 0xde, 0x89, 0x77,
	0xb6, 0xfb, 0x7a, 0xc4, 0x24, 0xbf, 0xdc, 0xb3, 0xf7, 0xf9, 0xf8, 0x6f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x67, 0xba, 0xe7, 0xab, 0xfa, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TokenServiceClient is the client API for TokenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TokenServiceClient interface {
	GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetTokenResponse, error)
	SetToken(ctx context.Context, in *SetTokenRequest, opts ...grpc.CallOption) (*SetTokenResponse, error)
	ProvideToken(ctx context.Context, opts ...grpc.CallOption) (TokenService_ProvideTokenClient, error)
}

type tokenServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenServiceClient(cc grpc.ClientConnInterface) TokenServiceClient {
	return &tokenServiceClient{cc}
}

func (c *tokenServiceClient) GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetTokenResponse, error) {
	out := new(GetTokenResponse)
	err := c.cc.Invoke(ctx, "/supervisor.TokenService/GetToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenServiceClient) SetToken(ctx context.Context, in *SetTokenRequest, opts ...grpc.CallOption) (*SetTokenResponse, error) {
	out := new(SetTokenResponse)
	err := c.cc.Invoke(ctx, "/supervisor.TokenService/SetToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenServiceClient) ProvideToken(ctx context.Context, opts ...grpc.CallOption) (TokenService_ProvideTokenClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TokenService_serviceDesc.Streams[0], "/supervisor.TokenService/ProvideToken", opts...)
	if err != nil {
		return nil, err
	}
	x := &tokenServiceProvideTokenClient{stream}
	return x, nil
}

type TokenService_ProvideTokenClient interface {
	Send(*ProvideTokenRequest) error
	Recv() (*ProvideTokenResponse, error)
	grpc.ClientStream
}

type tokenServiceProvideTokenClient struct {
	grpc.ClientStream
}

func (x *tokenServiceProvideTokenClient) Send(m *ProvideTokenRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *tokenServiceProvideTokenClient) Recv() (*ProvideTokenResponse, error) {
	m := new(ProvideTokenResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TokenServiceServer is the server API for TokenService service.
type TokenServiceServer interface {
	GetToken(context.Context, *GetTokenRequest) (*GetTokenResponse, error)
	SetToken(context.Context, *SetTokenRequest) (*SetTokenResponse, error)
	ProvideToken(TokenService_ProvideTokenServer) error
}

// UnimplementedTokenServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTokenServiceServer struct {
}

func (*UnimplementedTokenServiceServer) GetToken(ctx context.Context, req *GetTokenRequest) (*GetTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetToken not implemented")
}
func (*UnimplementedTokenServiceServer) SetToken(ctx context.Context, req *SetTokenRequest) (*SetTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetToken not implemented")
}
func (*UnimplementedTokenServiceServer) ProvideToken(srv TokenService_ProvideTokenServer) error {
	return status.Errorf(codes.Unimplemented, "method ProvideToken not implemented")
}

func RegisterTokenServiceServer(s *grpc.Server, srv TokenServiceServer) {
	s.RegisterService(&_TokenService_serviceDesc, srv)
}

func _TokenService_GetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenServiceServer).GetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/supervisor.TokenService/GetToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenServiceServer).GetToken(ctx, req.(*GetTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenService_SetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenServiceServer).SetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/supervisor.TokenService/SetToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenServiceServer).SetToken(ctx, req.(*SetTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenService_ProvideToken_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TokenServiceServer).ProvideToken(&tokenServiceProvideTokenServer{stream})
}

type TokenService_ProvideTokenServer interface {
	Send(*ProvideTokenResponse) error
	Recv() (*ProvideTokenRequest, error)
	grpc.ServerStream
}

type tokenServiceProvideTokenServer struct {
	grpc.ServerStream
}

func (x *tokenServiceProvideTokenServer) Send(m *ProvideTokenResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *tokenServiceProvideTokenServer) Recv() (*ProvideTokenRequest, error) {
	m := new(ProvideTokenRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _TokenService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "supervisor.TokenService",
	HandlerType: (*TokenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetToken",
			Handler:    _TokenService_GetToken_Handler,
		},
		{
			MethodName: "SetToken",
			Handler:    _TokenService_SetToken_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProvideToken",
			Handler:       _TokenService_ProvideToken_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "token.proto",
}
